package co.com.sirensaMotor.objetos.interno;
// Generated 12/01/2018 05:29:16 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblfactura generated by hbm2java
 */
public class Tblfactura  implements java.io.Serializable {


     private BigDecimal id;
     private Tblproveedor tblproveedor;
     private Tblparametrosdetalle tblparametrosdetalle;
     private Tblcliente tblcliente;
     private BigDecimal idusuario;
     private Character tipofactura;
     private String numerofactura;
     private Date fechafactura;
     private String identificacionvendedor;
     private String nombrevendedor;
     private BigDecimal subtotal;
     private BigDecimal iva;
     private BigDecimal descuento;
     private BigDecimal total;
     private Date fechacreacion;
     private Set tbldetallefacturas = new HashSet(0);
     private Set tbldevolucions = new HashSet(0);

    public Tblfactura() {
    }

	
    public Tblfactura(BigDecimal id) {
        this.id = id;
    }
    public Tblfactura(BigDecimal id, Tblproveedor tblproveedor, Tblparametrosdetalle tblparametrosdetalle, Tblcliente tblcliente, BigDecimal idusuario, Character tipofactura, String numerofactura, Date fechafactura, String identificacionvendedor, String nombrevendedor, BigDecimal subtotal, BigDecimal iva, BigDecimal descuento, BigDecimal total, Date fechacreacion, Set tbldetallefacturas, Set tbldevolucions) {
       this.id = id;
       this.tblproveedor = tblproveedor;
       this.tblparametrosdetalle = tblparametrosdetalle;
       this.tblcliente = tblcliente;
       this.idusuario = idusuario;
       this.tipofactura = tipofactura;
       this.numerofactura = numerofactura;
       this.fechafactura = fechafactura;
       this.identificacionvendedor = identificacionvendedor;
       this.nombrevendedor = nombrevendedor;
       this.subtotal = subtotal;
       this.iva = iva;
       this.descuento = descuento;
       this.total = total;
       this.fechacreacion = fechacreacion;
       this.tbldetallefacturas = tbldetallefacturas;
       this.tbldevolucions = tbldevolucions;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Tblproveedor getTblproveedor() {
        return this.tblproveedor;
    }
    
    public void setTblproveedor(Tblproveedor tblproveedor) {
        this.tblproveedor = tblproveedor;
    }
    public Tblparametrosdetalle getTblparametrosdetalle() {
        return this.tblparametrosdetalle;
    }
    
    public void setTblparametrosdetalle(Tblparametrosdetalle tblparametrosdetalle) {
        this.tblparametrosdetalle = tblparametrosdetalle;
    }
    public Tblcliente getTblcliente() {
        return this.tblcliente;
    }
    
    public void setTblcliente(Tblcliente tblcliente) {
        this.tblcliente = tblcliente;
    }
    public BigDecimal getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(BigDecimal idusuario) {
        this.idusuario = idusuario;
    }
    public Character getTipofactura() {
        return this.tipofactura;
    }
    
    public void setTipofactura(Character tipofactura) {
        this.tipofactura = tipofactura;
    }
    public String getNumerofactura() {
        return this.numerofactura;
    }
    
    public void setNumerofactura(String numerofactura) {
        this.numerofactura = numerofactura;
    }
    public Date getFechafactura() {
        return this.fechafactura;
    }
    
    public void setFechafactura(Date fechafactura) {
        this.fechafactura = fechafactura;
    }
    public String getIdentificacionvendedor() {
        return this.identificacionvendedor;
    }
    
    public void setIdentificacionvendedor(String identificacionvendedor) {
        this.identificacionvendedor = identificacionvendedor;
    }
    public String getNombrevendedor() {
        return this.nombrevendedor;
    }
    
    public void setNombrevendedor(String nombrevendedor) {
        this.nombrevendedor = nombrevendedor;
    }
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }
    public BigDecimal getIva() {
        return this.iva;
    }
    
    public void setIva(BigDecimal iva) {
        this.iva = iva;
    }
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }
    public Set getTbldetallefacturas() {
        return this.tbldetallefacturas;
    }
    
    public void setTbldetallefacturas(Set tbldetallefacturas) {
        this.tbldetallefacturas = tbldetallefacturas;
    }
    public Set getTbldevolucions() {
        return this.tbldevolucions;
    }
    
    public void setTbldevolucions(Set tbldevolucions) {
        this.tbldevolucions = tbldevolucions;
    }




}


