package co.com.sirensaMotor.objetos.interno;
// Generated 12/01/2018 05:29:16 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblproveedor generated by hbm2java
 */
public class Tblproveedor  implements java.io.Serializable {


     private BigDecimal id;
     private Tblusuario tblusuario;
     private Tblparametrosdetalle tblparametrosdetalle;
     private String nit;
     private String razonsocial;
     private String telefono;
     private String celular;
     private String direccion;
     private String ciudad;
     private Set tblfacturas = new HashSet(0);
     private Set tblpedidos = new HashSet(0);

    public Tblproveedor() {
    }

	
    public Tblproveedor(BigDecimal id, String nit, String razonsocial) {
        this.id = id;
        this.nit = nit;
        this.razonsocial = razonsocial;
    }
    public Tblproveedor(BigDecimal id, Tblusuario tblusuario, Tblparametrosdetalle tblparametrosdetalle, String nit, String razonsocial, String telefono, String celular, String direccion, String ciudad, Set tblfacturas, Set tblpedidos) {
       this.id = id;
       this.tblusuario = tblusuario;
       this.tblparametrosdetalle = tblparametrosdetalle;
       this.nit = nit;
       this.razonsocial = razonsocial;
       this.telefono = telefono;
       this.celular = celular;
       this.direccion = direccion;
       this.ciudad = ciudad;
       this.tblfacturas = tblfacturas;
       this.tblpedidos = tblpedidos;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Tblusuario getTblusuario() {
        return this.tblusuario;
    }
    
    public void setTblusuario(Tblusuario tblusuario) {
        this.tblusuario = tblusuario;
    }
    public Tblparametrosdetalle getTblparametrosdetalle() {
        return this.tblparametrosdetalle;
    }
    
    public void setTblparametrosdetalle(Tblparametrosdetalle tblparametrosdetalle) {
        this.tblparametrosdetalle = tblparametrosdetalle;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getRazonsocial() {
        return this.razonsocial;
    }
    
    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Set getTblfacturas() {
        return this.tblfacturas;
    }
    
    public void setTblfacturas(Set tblfacturas) {
        this.tblfacturas = tblfacturas;
    }
    public Set getTblpedidos() {
        return this.tblpedidos;
    }
    
    public void setTblpedidos(Set tblpedidos) {
        this.tblpedidos = tblpedidos;
    }




}


