package co.com.sirensaMotor.objetos.interno;
// Generated 12/01/2018 05:29:16 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblpedido generated by hbm2java
 */
public class Tblpedido  implements java.io.Serializable {


     private BigDecimal id;
     private Tblproveedor tblproveedor;
     private Tblusuario tblusuario;
     private Tblcliente tblcliente;
     private Date fechapedido;
     private String numeropedido;
     private Character tipopedido;
     private Set tbldetallepedidos = new HashSet(0);

    public Tblpedido() {
    }

	
    public Tblpedido(BigDecimal id) {
        this.id = id;
    }
    public Tblpedido(BigDecimal id, Tblproveedor tblproveedor, Tblusuario tblusuario, Tblcliente tblcliente, Date fechapedido, String numeropedido, Character tipopedido, Set tbldetallepedidos) {
       this.id = id;
       this.tblproveedor = tblproveedor;
       this.tblusuario = tblusuario;
       this.tblcliente = tblcliente;
       this.fechapedido = fechapedido;
       this.numeropedido = numeropedido;
       this.tipopedido = tipopedido;
       this.tbldetallepedidos = tbldetallepedidos;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Tblproveedor getTblproveedor() {
        return this.tblproveedor;
    }
    
    public void setTblproveedor(Tblproveedor tblproveedor) {
        this.tblproveedor = tblproveedor;
    }
    public Tblusuario getTblusuario() {
        return this.tblusuario;
    }
    
    public void setTblusuario(Tblusuario tblusuario) {
        this.tblusuario = tblusuario;
    }
    public Tblcliente getTblcliente() {
        return this.tblcliente;
    }
    
    public void setTblcliente(Tblcliente tblcliente) {
        this.tblcliente = tblcliente;
    }
    public Date getFechapedido() {
        return this.fechapedido;
    }
    
    public void setFechapedido(Date fechapedido) {
        this.fechapedido = fechapedido;
    }
    public String getNumeropedido() {
        return this.numeropedido;
    }
    
    public void setNumeropedido(String numeropedido) {
        this.numeropedido = numeropedido;
    }
    public Character getTipopedido() {
        return this.tipopedido;
    }
    
    public void setTipopedido(Character tipopedido) {
        this.tipopedido = tipopedido;
    }
    public Set getTbldetallepedidos() {
        return this.tbldetallepedidos;
    }
    
    public void setTbldetallepedidos(Set tbldetallepedidos) {
        this.tbldetallepedidos = tbldetallepedidos;
    }




}


