package co.com.sirensaMotor.objetos.interno;
// Generated 12/01/2018 05:29:16 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblusuario generated by hbm2java
 */
public class Tblusuario  implements java.io.Serializable {


     private BigDecimal id;
     private BigDecimal tipoidentificacion;
     private BigDecimal identificacion;
     private String nombreusuario;
     private String rol;
     private String passwords;
     private Set tblproveedors = new HashSet(0);
     private Set tblinventarios = new HashSet(0);
     private Set tblrols = new HashSet(0);
     private Set tblproductos = new HashSet(0);
     private Set tblpedidos = new HashSet(0);
     private Set tblclientes = new HashSet(0);
     private Set tbldevolucions = new HashSet(0);

    public Tblusuario() {
    }

	
    public Tblusuario(BigDecimal id) {
        this.id = id;
    }
    public Tblusuario(BigDecimal id, BigDecimal tipoidentificacion, BigDecimal identificacion, String nombreusuario, String rol, String passwords, Set tblproveedors, Set tblinventarios, Set tblrols, Set tblproductos, Set tblpedidos, Set tblclientes, Set tbldevolucions) {
       this.id = id;
       this.tipoidentificacion = tipoidentificacion;
       this.identificacion = identificacion;
       this.nombreusuario = nombreusuario;
       this.rol = rol;
       this.passwords = passwords;
       this.tblproveedors = tblproveedors;
       this.tblinventarios = tblinventarios;
       this.tblrols = tblrols;
       this.tblproductos = tblproductos;
       this.tblpedidos = tblpedidos;
       this.tblclientes = tblclientes;
       this.tbldevolucions = tbldevolucions;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public BigDecimal getTipoidentificacion() {
        return this.tipoidentificacion;
    }
    
    public void setTipoidentificacion(BigDecimal tipoidentificacion) {
        this.tipoidentificacion = tipoidentificacion;
    }
    public BigDecimal getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(BigDecimal identificacion) {
        this.identificacion = identificacion;
    }
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getPasswords() {
        return this.passwords;
    }
    
    public void setPasswords(String passwords) {
        this.passwords = passwords;
    }
    public Set getTblproveedors() {
        return this.tblproveedors;
    }
    
    public void setTblproveedors(Set tblproveedors) {
        this.tblproveedors = tblproveedors;
    }
    public Set getTblinventarios() {
        return this.tblinventarios;
    }
    
    public void setTblinventarios(Set tblinventarios) {
        this.tblinventarios = tblinventarios;
    }
    public Set getTblrols() {
        return this.tblrols;
    }
    
    public void setTblrols(Set tblrols) {
        this.tblrols = tblrols;
    }
    public Set getTblproductos() {
        return this.tblproductos;
    }
    
    public void setTblproductos(Set tblproductos) {
        this.tblproductos = tblproductos;
    }
    public Set getTblpedidos() {
        return this.tblpedidos;
    }
    
    public void setTblpedidos(Set tblpedidos) {
        this.tblpedidos = tblpedidos;
    }
    public Set getTblclientes() {
        return this.tblclientes;
    }
    
    public void setTblclientes(Set tblclientes) {
        this.tblclientes = tblclientes;
    }
    public Set getTbldevolucions() {
        return this.tbldevolucions;
    }
    
    public void setTbldevolucions(Set tbldevolucions) {
        this.tbldevolucions = tbldevolucions;
    }




}


