package co.com.sirensaMotor.objetos.interno;
// Generated 12/01/2018 05:29:16 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Tbldevolucion generated by hbm2java
 */
public class Tbldevolucion  implements java.io.Serializable {


     private BigDecimal id;
     private Tblusuario tblusuario;
     private Tblproducto tblproducto;
     private Tblfactura tblfactura;
     private Date fechadevolucion;
     private String observacion;

    public Tbldevolucion() {
    }

	
    public Tbldevolucion(BigDecimal id, Tblproducto tblproducto, Tblfactura tblfactura) {
        this.id = id;
        this.tblproducto = tblproducto;
        this.tblfactura = tblfactura;
    }
    public Tbldevolucion(BigDecimal id, Tblusuario tblusuario, Tblproducto tblproducto, Tblfactura tblfactura, Date fechadevolucion, String observacion) {
       this.id = id;
       this.tblusuario = tblusuario;
       this.tblproducto = tblproducto;
       this.tblfactura = tblfactura;
       this.fechadevolucion = fechadevolucion;
       this.observacion = observacion;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Tblusuario getTblusuario() {
        return this.tblusuario;
    }
    
    public void setTblusuario(Tblusuario tblusuario) {
        this.tblusuario = tblusuario;
    }
    public Tblproducto getTblproducto() {
        return this.tblproducto;
    }
    
    public void setTblproducto(Tblproducto tblproducto) {
        this.tblproducto = tblproducto;
    }
    public Tblfactura getTblfactura() {
        return this.tblfactura;
    }
    
    public void setTblfactura(Tblfactura tblfactura) {
        this.tblfactura = tblfactura;
    }
    public Date getFechadevolucion() {
        return this.fechadevolucion;
    }
    
    public void setFechadevolucion(Date fechadevolucion) {
        this.fechadevolucion = fechadevolucion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


