package co.com.sirensaMotor.objetos.interno;
// Generated 12/01/2018 05:29:16 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Tbldetallefactura generated by hbm2java
 */
public class Tbldetallefactura  implements java.io.Serializable {


     private BigDecimal id;
     private Tblproducto tblproducto;
     private Tblfactura tblfactura;
     private BigDecimal idpresentacion;
     private BigDecimal valorunitario;
     private BigDecimal ivaunitario;
     private BigDecimal cantidad;
     private BigDecimal descuento;
     private BigDecimal total;

    public Tbldetallefactura() {
    }

	
    public Tbldetallefactura(BigDecimal id, Tblfactura tblfactura) {
        this.id = id;
        this.tblfactura = tblfactura;
    }
    public Tbldetallefactura(BigDecimal id, Tblproducto tblproducto, Tblfactura tblfactura, BigDecimal idpresentacion, BigDecimal valorunitario, BigDecimal ivaunitario, BigDecimal cantidad, BigDecimal descuento, BigDecimal total) {
       this.id = id;
       this.tblproducto = tblproducto;
       this.tblfactura = tblfactura;
       this.idpresentacion = idpresentacion;
       this.valorunitario = valorunitario;
       this.ivaunitario = ivaunitario;
       this.cantidad = cantidad;
       this.descuento = descuento;
       this.total = total;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Tblproducto getTblproducto() {
        return this.tblproducto;
    }
    
    public void setTblproducto(Tblproducto tblproducto) {
        this.tblproducto = tblproducto;
    }
    public Tblfactura getTblfactura() {
        return this.tblfactura;
    }
    
    public void setTblfactura(Tblfactura tblfactura) {
        this.tblfactura = tblfactura;
    }
    public BigDecimal getIdpresentacion() {
        return this.idpresentacion;
    }
    
    public void setIdpresentacion(BigDecimal idpresentacion) {
        this.idpresentacion = idpresentacion;
    }
    public BigDecimal getValorunitario() {
        return this.valorunitario;
    }
    
    public void setValorunitario(BigDecimal valorunitario) {
        this.valorunitario = valorunitario;
    }
    public BigDecimal getIvaunitario() {
        return this.ivaunitario;
    }
    
    public void setIvaunitario(BigDecimal ivaunitario) {
        this.ivaunitario = ivaunitario;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }




}


