package co.com.sirensaMotor.objetos.interno;
// Generated 12/01/2018 05:29:16 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblparametrosdetalle generated by hbm2java
 */
public class Tblparametrosdetalle  implements java.io.Serializable {


     private BigDecimal id;
     private Tblparametros tblparametros;
     private String descripcionDetalle;
     private String abreviatura;
     private String valor;
     private Set tblfacturas = new HashSet(0);
     private Set tblproveedors = new HashSet(0);
     private Set tblclientes = new HashSet(0);

    public Tblparametrosdetalle() {
    }

	
    public Tblparametrosdetalle(BigDecimal id, Tblparametros tblparametros, String valor) {
        this.id = id;
        this.tblparametros = tblparametros;
        this.valor = valor;
    }
    public Tblparametrosdetalle(BigDecimal id, Tblparametros tblparametros, String descripcionDetalle, String abreviatura, String valor, Set tblfacturas, Set tblproveedors, Set tblclientes) {
       this.id = id;
       this.tblparametros = tblparametros;
       this.descripcionDetalle = descripcionDetalle;
       this.abreviatura = abreviatura;
       this.valor = valor;
       this.tblfacturas = tblfacturas;
       this.tblproveedors = tblproveedors;
       this.tblclientes = tblclientes;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Tblparametros getTblparametros() {
        return this.tblparametros;
    }
    
    public void setTblparametros(Tblparametros tblparametros) {
        this.tblparametros = tblparametros;
    }
    public String getDescripcionDetalle() {
        return this.descripcionDetalle;
    }
    
    public void setDescripcionDetalle(String descripcionDetalle) {
        this.descripcionDetalle = descripcionDetalle;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public Set getTblfacturas() {
        return this.tblfacturas;
    }
    
    public void setTblfacturas(Set tblfacturas) {
        this.tblfacturas = tblfacturas;
    }
    public Set getTblproveedors() {
        return this.tblproveedors;
    }
    
    public void setTblproveedors(Set tblproveedors) {
        this.tblproveedors = tblproveedors;
    }
    public Set getTblclientes() {
        return this.tblclientes;
    }
    
    public void setTblclientes(Set tblclientes) {
        this.tblclientes = tblclientes;
    }




}


