package co.com.sirensaMotor.objetos.interno;
// Generated 12/01/2018 05:29:16 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Tblrol generated by hbm2java
 */
public class Tblrol  implements java.io.Serializable {


     private BigDecimal id;
     private Tblusuario tblusuario;
     private String nombrerol;

    public Tblrol() {
    }

	
    public Tblrol(BigDecimal id) {
        this.id = id;
    }
    public Tblrol(BigDecimal id, Tblusuario tblusuario, String nombrerol) {
       this.id = id;
       this.tblusuario = tblusuario;
       this.nombrerol = nombrerol;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Tblusuario getTblusuario() {
        return this.tblusuario;
    }
    
    public void setTblusuario(Tblusuario tblusuario) {
        this.tblusuario = tblusuario;
    }
    public String getNombrerol() {
        return this.nombrerol;
    }
    
    public void setNombrerol(String nombrerol) {
        this.nombrerol = nombrerol;
    }




}


